
[platformio]
default_envs = lilygo-t3-v16
src_dir = .

[env:lilygo-t3-v16]
platform = espressif32@^6.6.0
board = ttgo-lora32-v1
framework = arduino

; LilyGO T3 V1.6.1
upload_port = /dev/ttyACM1
monitor_port = /dev/ttyACM1
monitor_speed = 115200

; QP/C++ from our working qp-lab installation.
; RadioLib from the working E1 LoRa experiment.
lib_deps =
    /home/smr/projects/qpcpp_esp32
    jgromes/RadioLib

build_flags =
    -D QP_CPU_NUM=1
    -D CONFIG_QP_IDLE_YIELD
    -D Q_SPY
    -D LILYGO_T3
    -D CORE_DEBUG_LEVEL=0

    ; QM-generated application headers
    -Imodel/generated

    ; Collab-generated signal definitions
    -Imodel

    ; Shared telemetry protocol
    -I../protocol

build_src_filter =
    +<src/*.cpp>
    +<model/generated/*.cpp>
