#!/usr/bin/env python3
"""
Generate QSPY signal/object dictionary include from a QM model file.

Extracts:
  1. Signal names from enum ...Signals... in generated bsp.hpp text
  2. AO_* object declarations from QM XML attributes

Outputs:
  src/generated/qs_dict.inc

Example:
  python3 tools/generate_qs_dict.py src/blinky_button.qm

Without #ifdef Q_SPY wrapper:
  python3 tools/generate_qs_dict.py src/blinky_button.qm --no-guard
"""

from __future__ import annotations

import argparse
import re
import xml.etree.ElementTree as ET
from pathlib import Path


SENTINELS = {
    "MAX_SIG",
    "MAX_PUB_SIG",
    "MAX_RESERVED_SIG",
}


def strip_comments(text: str) -> str:
    """Remove C/C++ comments."""
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//.*", "", text)
    return text


def unique(items):
    """Preserve order while removing duplicates."""
    out = []
    seen = set()

    for item in items:
        if item not in seen:
            seen.add(item)
            out.append(item)

    return out


def extract_generated_file_text(root: ET.Element, filename: str) -> str:
    """
    Extract embedded generated file text from QM XML.

    Example:
      <file name="bsp.hpp">
         <text>...</text>
      </file>
    """
    for file_el in root.findall(".//file"):
        if file_el.attrib.get("name") == filename:
            text_el = file_el.find("text")
            return text_el.text or ""

    return ""


def find_signals_from_bsp_hpp(root: ET.Element) -> list[str]:
    """
    Find enum entries from something like:

      enum BlinkySignals {
          TIMEOUT_SIG = QP::Q_USER_SIG,
          BUTTON_CLICK_SIG,
          MAX_SIG
      };
    """

    text = extract_generated_file_text(root, "bsp.hpp")
    clean = strip_comments(text)

    enum_re = re.compile(
        r"""
        enum
        \s+
        \w*Signals\w*
        \s*
        \{
        (?P<body>.*?)
        \}
        \s*;
        """,
        re.DOTALL | re.VERBOSE,
    )

    signals = []

    for match in enum_re.finditer(clean):
        body = match.group("body")

        for item in body.split(","):
            item = item.strip()

            if not item:
                continue

            # Remove assignment if present
            # e.g. TIMEOUT_SIG = QP::Q_USER_SIG
            name = item.split("=")[0].strip()

            if not re.fullmatch(r"[A-Za-z_]\w*", name):
                continue

            if name in SENTINELS:
                continue

            if not name.endswith("_SIG"):
                continue

            signals.append(name)

    return unique(signals)


def find_ao_objects(root: ET.Element) -> list[str]:
    """
    Find AO declarations from QM XML attributes like:

      <attribute
          name="AO_Blinky"
          type="QP::QActive * const"
      />
    """

    aos = []

    for attr in root.findall(".//attribute"):
        name = attr.attrib.get("name", "")
        typ = attr.attrib.get("type", "")

        if name.startswith("AO_") and "QActive" in typ:
            aos.append(name)

    return unique(aos)


def generate(
    signals: list[str],
    aos: list[str],
    source: Path,
    emit_guard: bool = True,
) -> str:

    lines = [
        "// Auto-generated by tools/generate_qs_dict.py",
        f"// Source model: {source}",
        "// Do not edit by hand.",
        "",
    ]

    if emit_guard:
        lines += [
            "#ifdef Q_SPY",
            "",
        ]

    # ---------------------------------------------------------
    # Signal dictionaries
    # ---------------------------------------------------------

    lines.append("// Signal dictionaries")

    if signals:
        for sig in signals:
            lines.append(f"QS_SIG_DICTIONARY({sig}, nullptr);")
    else:
        lines.append("// WARNING: no signals found")

    lines.append("")

    # ---------------------------------------------------------
    # AO dictionaries
    # ---------------------------------------------------------

    lines.append("// Active object dictionaries")

    if aos:
        for ao in aos:
            lines.append(f"QS_OBJ_DICTIONARY({ao});")
    else:
        lines.append("// WARNING: no active objects found")

    if emit_guard:
        lines += [
            "",
            "#endif // Q_SPY",
        ]

    lines.append("")

    return "\n".join(lines)


def main() -> int:

    ap = argparse.ArgumentParser()

    ap.add_argument(
        "model",
        type=Path,
        help="Path to QM model file",
    )

    ap.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("src/generated/qs_dict.inc"),
        help="Output include file",
    )

    ap.add_argument(
        "--no-guard",
        action="store_true",
        help="Do not emit #ifdef Q_SPY wrapper",
    )

    args = ap.parse_args()

    if not args.model.exists():
        raise SystemExit(f"Model file not found: {args.model}")

    root = ET.parse(args.model).getroot()

    signals = find_signals_from_bsp_hpp(root)
    aos = find_ao_objects(root)

    output = generate(
        signals,
        aos,
        args.model,
        emit_guard=not args.no_guard,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")

    print(f"Generated {args.output}")
    print(f"  signals: {', '.join(signals) or '(none)'}")
    print(f"  objects : {', '.join(aos) or '(none)'}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())